### ISSUE TITLE
As a task creator and task taker I would like to see everyone who has completed a task on the dashboard.

### ISSUE THREAD

**Issue by LisaLNelson** [18F/open-opportunities-theme#98]
All the information on completed tasks and who worked on them has vanished from the left side of the page.
![screen shot 2016-03-23 at 2 26 41 pm](https://cloud.githubusercontent.com/assets/9039852/13996267/50351cf0-f103-11e5-9c62-aced8ca40b5a.png)

**Comment by ultrasaurus** [comment]
I think this got resolved a while back
